### PR TITLE
partly fix paste UTF-8 string from clipboard.

### PR DESCRIPTION
**Pull request by ZhiZe-ZG**
When copy UTF-8 string from clipboard,  your code may lead to mistaken code. I try to fix it by using `utf8_to_wide` instead your string convert.

### CODE REVIEW

**Comment by SmallJoker** [comment]
Wow. This is the first time I got a PR in a forked repository.

I tried to paste the following Unicode sequences:

`早上好` -> results in `\u65e9\u4e0a\u597d`
`荈⣬冋䠈ঋᇨ` (random binary content I found) -> results in `\u8348\u28ec\u518b\u4808\u098b\u11e8`

This is the same behaviour as seen in the current Minetest master branch. Which kind of inputs does it fix? Would you have some examples?

**Comment by ZhiZe-ZG** [comment]
@SmallJoker It seam like your system clipboard using UTF-16 rather than UTF-8.

I found that the Chinese coded in the Lua script can be output normally on the console, but copy and paste cannot. So I imitated imitated the ModApiServer::l_chat_send_all function in lua_api/l_server.cpp file.

The ModApiServer::l_chat_send_all assumed that lua souce code is encoded in UTF-8,  so it call utf8_to_wide to parse the char string text. I did the same thing in your code.

The key is parse byte string, not getTextFromClipboard. So the value variable text in your code didn't change, but the value passed to  prompt.input changed.

There are at least 5 type Chinese encodings（the situation in Japanese is similar）. If the encoding supporting by your system is not UTF-8, the console still output wrong characters, even after my fix.

My fix is for the following situations:

The string you copy from clipboard is encoded in  UTF-8 but return as char*. In your code you treat them as ASCII string. One ASCII character take 1 byte, but one Chinese character in UTF-8 take 3 bytes.  So “早” in UTF-8 should be "\xE6\x97\xA9" (as char*). utf8_to_wide trans it into wstring correctly. Your code seems to convert “早” to three ASCII characters.

But this still don't work on your system. Because you system use UTF-16 encoding. Here comes the most complicated part. I guess your system is windows. We all know Unicode just give every character a index number. UTF-8 and UTF-16 trans the index number into char* or int16*. But Windows call UTF-16 as "Unicode" and use it as the default Chinese encoding scheme for non-Chinese regions while UTF-8 is widely used on the internet. And for most Chinese region it use GBK encoding (based on int16, but not same as UTF-16).

So my suggestion is at least let the console support UTF-8, just like Lua scripts. Secondly, it supports UTF-16 for specific systems like Windows. GBK is a historical relic, so don't worry about it for now. But if we want more Chinese players to join, this will be a must. until Microsoft abandoned GBK. 

This is not just a problem for the Chinese area, most areas not covered by ASCII encoding may face this problem. Fix clipboard is the first step, further purpose is supporting IME.  This is also the problem that Minecraft faced (I remember MC 1.8 fixed it completely and officially). 

This reply is a bit long.  This is also a tricky problem for programmers in non-ASCII areas.

**Comment by ZhiZe-ZG** [comment]
@SmallJoker I find something new, in irrlicht 1.8.4, COSOperator.cpp, line 96 to 110.
```
//! gets text from the clipboard
//! \return Returns 0 if no string is in there.
const c8* COSOperator::getTextFromClipboard() const
{
#if defined(_IRR_XBOX_PLATFORM_)
		return 0;
#elif defined(_IRR_WINDOWS_API_)
	if (!OpenClipboard(NULL))
		return 0;

	char * buffer = 0;

	HANDLE hData = GetClipboardData( CF_TEXT );
	buffer = (char*)GlobalLock( hData );
	GlobalUnlock( hData );
	CloseClipboard();
	return buffer;
```
irrlicht GetClipboardData in CF_TEXT mode. This will return GBK (or some other non-UTF encoding) when system language is Chinese. If write a new function and use CF_UNICODETEXT, we will get UTF-16.  All that remain is write a utf16_to_wtring function.

> https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getclipboarddata

> https://docs.microsoft.com/en-us/windows/win32/dataxchg/standard-clipboard-formats

> https://www.codeproject.com/Questions/262894/Copying-UTF-8-data-to-Clipboard

**Comment by SmallJoker** [comment]
Ubuntu 20.04.1 LTS, 64-bit
Pasting from the xorg clipboard has always been a bit buggy, hence I wouldn't be surprised to see bugs on Irrlicht- and Minetest-side. No idea about Windows - I don't have a cross-compile setup yet to test that.

Thanks for your research so far. I'll check whether there's something going on in the Linux part.

**Comment by ZhiZe-ZG** [comment]
@SmallJoker Perhaps minetest need a new reliable os abstract in these part. how about icu4c?

**Comment by SmallJoker** [comment]
Included the commit in my PR. Would you please be so nice and include your suggestions and conclusions in a related minetest/minetest issue?

**Pull request closed without merging**
